version: '3.8'

services:
  machine:
    build: ./machine
    container_name: ${NAME:-ctf_multi_machine}
    ports:
      - "${PORTOUT:-8080}:${PORTIN:-80}"
      - "2222:22"     # Puerto SSH
      - "1337:1337"   # Puerto del servicio secreto
    networks:
      - ctf_net
    restart: always

networks:
  ctf_net:
    driver: bridge